//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prOneEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int ID_Books { get; set; }
        public string Books_name { get; set; }
        public int Authors_ID { get; set; }
        public int Genres_ID { get; set; }
    
        public virtual Authors Authors { private get; set; }
        public virtual Genres Genres { private get; set; }
    }
}
